# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Baracoda Group (Baracoda AI Labs)
"""Controls on the final test (Table 7 of the paper): v1.2 vs Tekken after removing the sentence occurrences that
overlap the v1.2 training data (from results/contamination.json), and the equal ordinary-token budget control
(tokenizers/controls/baracoda-fr-v1_2-equal-ordinary-budget.json: 130,072 ordinary + 4 special tokens, as Tekken's
130,072 ordinary + 1,000 special). Needs results/counts.json (run.py eval) and results/contamination.json.
Writes results/controls.json and results/CONTROLS.md."""
import json
from tokenizers import Tokenizer
from common import RESULTS, ROOT, config, load
from evaluate import block_ci

MAIN, REF = "baracoda-fr-v1_2", "tekken"


def main():
    counts = json.loads((RESULTS / "counts.json").read_text())["counts"]
    cont = json.loads((RESULTS / "contamination.json").read_text())
    final, cfg = load("final"), config()
    bad = {}
    for x in cont["contaminated"]:
        bad.setdefault(x["corpus"], set()).add(x["index"])
    eq = Tokenizer.from_file(str(ROOT / "tokenizers" / "controls" / "baracoda-fr-v1_2-equal-ordinary-budget.json"))
    out = {"overlap_removed": {}, "equal_ordinary_budget": {}}
    L = ["# Controls on the final test (generated by scripts/controls.py)", "",
         "## Overlap with training data removed", "",
         "| Corpus | Sentences | > 40 chars | Overlap | Retained | v1.2 | Tekken | v1.2 vs Tekken (95% CI) |",
         "|---|---:|---:|---:|---:|---:|---:|---|"]
    pooled = {}
    for n, sents in final.items():
        keep = [i for i in range(len(sents)) if i not in bad.get(n, set())]
        a = [counts[MAIN][n][i] for i in keep]; b = [counts[REF][n][i] for i in keep]
        d = block_ci(a, b)
        c = cont["corpora"][n]
        out["overlap_removed"][n] = {"sentences": len(sents), "eligible": c["eligible_over_40_chars"],
                                     "overlap": len(bad.get(n, ())), "retained": len(keep), "v1_2": sum(a), "tekken": sum(b), "gain_ci": d}
        L.append(f"| {n} | {len(sents)} | {c['eligible_over_40_chars']} | {len(bad.get(n, ()))} | {len(keep)} | {sum(a):,} | {sum(b):,} | "
                 f"{100*d[0]:+.2f} % [{100*d[1]:+.2f}, {100*d[2]:+.2f}] |")
        p = pooled.setdefault(cfg[n]["lang"], [[], []]); p[0] += a; p[1] += b
    for lang, (a, b) in pooled.items():
        d = block_ci(a, b)
        out["overlap_removed"][f"{lang} pooled"] = {"retained": len(a), "v1_2": sum(a), "tekken": sum(b), "gain_ci": d}
        L.append(f"| **{lang} pooled** | | | | {len(a)} | {sum(a):,} | {sum(b):,} | **{100*d[0]:+.2f} %** [{100*d[1]:+.2f}, {100*d[2]:+.2f}] |")
    L += ["", "## Equal ordinary-token budget (all sentences)", "",
          "| Language | Control | v1.2 | Tekken | Control vs Tekken (95% CI) | v1.2 vs Tekken |", "|---|---:|---:|---:|---|---|"]
    for lang in ["fr", "en"]:
        ns = [n for n in final if cfg[n]["lang"] == lang]
        e = sum(([len(x.ids) for x in eq.encode_batch(final[n], add_special_tokens=False)] for n in ns), [])
        v = sum((counts[MAIN][n] for n in ns), []); t = sum((counts[REF][n] for n in ns), [])
        d, dv = block_ci(e, t), block_ci(v, t)
        out["equal_ordinary_budget"][lang] = {"control": sum(e), "v1_2": sum(v), "tekken": sum(t), "control_vs_tekken": d, "v1_2_vs_tekken": dv}
        L.append(f"| {lang} | {sum(e):,} | {sum(v):,} | {sum(t):,} | {100*d[0]:+.3f} % [{100*d[1]:+.2f}, {100*d[2]:+.2f}] | {100*dv[0]:+.3f} % |")
    (RESULTS / "controls.json").write_text(json.dumps(out, indent=1))
    (RESULTS / "CONTROLS.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
