# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Baracoda Group (Baracoda AI Labs)
"""Count tokens sentence by sentence (no special tokens) for every tokenizer on every corpus, check the
protocol's hypotheses on the final test, and write results/counts.json and results/TABLES.md.

Tokenizers: Baracoda FR files in tokenizers/, Mistral Tekken (mistral-common 1.12.0, tekken_240911.json),
OpenAI o200k (tiktoken), CroissantLLM (croissantllm/CroissantLLMBase tokenizer.json from Hugging Face).
A tokenizer that cannot be loaded is reported and skipped; use --require-all to fail instead."""
import argparse, json
from pathlib import Path
import numpy as np
from common import CORPORA, RESULTS, TOKENIZERS, config, load, safe


def groups_of(name):
    p = CORPORA / f"{safe(name)}.groups.json"
    return json.loads(p.read_text()) if p.exists() else None


def baracoda(path):
    from tokenizers import Tokenizer
    t = Tokenizer.from_file(str(path))
    return lambda L: [len(e.ids) for e in t.encode_batch(L, add_special_tokens=False)]


def tekken():
    import mistral_common
    from mistral_common.tokens.tokenizers.tekken import Tekkenizer
    t = Tekkenizer.from_file(str(next(Path(mistral_common.__file__).parent.rglob("tekken_240911.json"))))
    return lambda L: [len(t.encode(s, bos=False, eos=False)) for s in L]


def o200k():
    import tiktoken
    e = tiktoken.get_encoding("o200k_base")
    return lambda L: [len(x) for x in e.encode_ordinary_batch(L)]


def croissant():
    from huggingface_hub import hf_hub_download
    from tokenizers import Tokenizer
    t = Tokenizer.from_file(hf_hub_download("croissantllm/CroissantLLMBase", "tokenizer.json"))
    return lambda L: [len(e.ids) for e in t.encode_batch(L, add_special_tokens=False)]


def block_ci(a, b, bs=10, reps=2000, seed=0, groups=None):
    """Paired bootstrap over documents (when document ids are given, e.g. NTREX DOCUMENT_IDS.tsv) or else
    over blocks of `bs` consecutive sentences; returns (ratio-1, low, high)."""
    a, b = np.asarray(a), np.asarray(b)
    rng = np.random.default_rng(seed)
    if groups is not None:
        order = list(dict.fromkeys(groups))
        blocks = [np.array([i for i, g in enumerate(groups) if g == d]) for d in order]
    else:
        blocks = [np.arange(i, min(i + bs, len(a))) for i in range(0, len(a), bs)]
    r = [a[idx].sum() / b[idx].sum() - 1 for idx in
         (np.concatenate([blocks[j] for j in rng.integers(0, len(blocks), len(blocks))]) for _ in range(reps))]
    return float(a.sum() / b.sum() - 1), float(np.percentile(r, 2.5)), float(np.percentile(r, 97.5))


def pct(x):
    return f"{100 * x:+.2f} %"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--require-all", action="store_true")
    args = ap.parse_args()
    toks = {p.stem: (lambda p=p: baracoda(p)) for p in sorted(TOKENIZERS.glob("*.json"))}
    toks.update({"tekken": tekken, "o200k": o200k, "croissant": croissant})
    corpora = {**load("dev"), **load("final")}
    counts, skipped = {}, {}
    for name, make in toks.items():
        try:
            f = make()
        except Exception as e:  # network or package missing
            if args.require_all:
                raise
            skipped[name] = repr(e)[:200]
            continue
        counts[name] = {c: f(L) for c, L in corpora.items()}
        print("counted", name, flush=True)
    RESULTS.mkdir(exist_ok=True)
    (RESULTS / "counts.json").write_text(json.dumps({"counts": counts, "skipped": skipped}))
    if counts["tekken"]["UD French-PUD"] and sum(counts["tekken"]["UD French-PUD"]) != 29707:
        raise SystemExit(f"Sanity check failed: Tekken on UD French-PUD = {sum(counts['tekken']['UD French-PUD'])}, expected 29707")
    cfg = config()
    main_tok = "baracoda-fr-v1_2"
    L = ["# Results (generated by scripts/evaluate.py; do not edit by hand)", "",
         "95% intervals: paired bootstrap (2,000 draws) over NTREX documents (DOCUMENT_IDS.tsv, 123 documents) for NTREX,"
         " over blocks of 10 consecutive sentences for Universal Dependencies corpora.", ""]
    if skipped:
        L += ["Skipped tokenizers (could not be loaded): " + ", ".join(f"{k} ({v})" for k, v in skipped.items()), ""]
    for role in ["dev", "final"]:
        names = [n for n in corpora if cfg[n]["role"] == role]
        L += [f"## {'Development and monitoring benchmarks' if role == 'dev' else 'Final test (protocol declared fixed before the test)'} (tokens)", "",
              "| Corpus | Sentences | " + " | ".join(counts) + " | v1.2 vs Tekken (95% CI) |",
              "|---|---:|" + "---:|" * len(counts) + "---|"]
        for n in names:
            d, lo, hi = block_ci(counts[main_tok][n], counts["tekken"][n], groups=groups_of(n))
            L.append(f"| {n} | {len(corpora[n])} | " + " | ".join(f"{sum(counts[t][n]):,}" for t in counts)
                     + f" | {pct(d)} [{pct(lo)}, {pct(hi)}] |")
        if role == "final":
            H = {}
            for lang in ["fr", "en"]:
                ns = [n for n in names if cfg[n]["lang"] == lang]
                a = sum((counts[main_tok][n] for n in ns), []); b = sum((counts["tekken"][n] for n in ns), [])
                d, lo, hi = block_ci(a, b)
                L.append(f"| **{lang} pooled** | {sum(len(corpora[n]) for n in ns)} | "
                         + " | ".join(f"{sum(sum(counts[t][n]) for n in ns):,}" for t in counts) + f" | **{pct(d)}** [{pct(lo)}, {pct(hi)}] |")
                H[lang] = d
            fr = [n for n in names if cfg[n]["lang"] == "fr"]
            L += ["", "Hypotheses fixed in protocol/PROTOCOLE.md:",
                  f"- H1 (fewer tokens than Tekken on each French corpus): {all(sum(counts[main_tok][n]) < sum(counts['tekken'][n]) for n in fr)}",
                  f"- H1b (at least 8% fewer on pooled French): {H['fr'] <= -0.08} ({pct(H['fr'])})",
                  f"- H2 (at most 2% more on pooled English): {H['en'] <= 0.02} ({pct(H['en'])})"]
        L.append("")
    pairs = {}
    for n, c in cfg.items():
        if "pair" in c:
            pairs.setdefault(c["pair"], {})[c["lang"]] = n
    L += ["## French/English premium on parallel corpora", "", "| Pair | " + " | ".join(counts) + " |", "|---|" + "---:|" * len(counts)]
    for p, d in pairs.items():
        L.append(f"| {p} | " + " | ".join(f"{sum(counts[t][d['fr']]) / sum(counts[t][d['en']]):.3f}" for t in counts) + " |")
    (RESULTS / "TABLES.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
